---
- hosts: localhost
  connection: localhost
  become: yes
  # gather_facts: false

  vars_files:
    - vars.yml

  roles:
    # - geerlingguy.firewall
    # - geerlingguy.ntp
    - geerlingguy.repo-epel
    # - geerlingguy.pip
    # - geerlingguy.docker
    - roles/ansible-role-vagrant
    # - andrewrothstein.docker-machine

  tasks:
    # - include_tasks: tasks/rh_subscription_simple.yml
    #   when: ansible_distribution == 'RedHat'

    # - include_tasks: tasks/software.yml
